#!/usr/bin/env bash
set -euo pipefail

# Turn the current (fully configured) device into a GOLDEN IMAGE template:
# de-personalise it so the eMMC can be imaged and written to many identical
# units. Per-unit identity (machine-id, SSH host keys, hostname, WebUI session
# secret) is stripped here and regenerated on each clone's first boot by
# vision-firstboot.service.
#
# Run this on the golden device, then power off and read the eMMC to a .img.
#
# PRECONDITIONS
#   - Same hardware as the target fleet (module + base board).
#   - Read-only overlay DISABLED (run install/21_disable_readonly_overlay.sh
#     first). This script refuses to run under an active overlay.
#
# Usage: sudo scripts/prepare-golden-image.sh

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

require_root

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
GATEWAY_HOME=$(cd "$SCRIPT_DIR/.." && pwd)
STATE_DIR=/srv/vision_mirror/.state
SEED_DIR=/etc/citostore-seed

if grep -qw overlayroot /proc/cmdline 2>/dev/null || \
   findmnt -no FSTYPE / 2>/dev/null | grep -q overlay; then
  echo "read-only overlay is active; run install/21_disable_readonly_overlay.sh and reboot first" >&2
  exit 1
fi

log "quiescing services"
systemctl stop vision-sync.timer vision-sync-fast.timer vision-monitor.timer \
  vision-rotator.timer vision-webui.service smbd nmbd 2>/dev/null || true

# 1) Stash the SHARED secrets onto the eMMC so first-boot can seed them back
#    into .state (which lives on the per-unit empty NVMe and does not travel
#    with the eMMC image).
mkdir -p "$SEED_DIR"
chmod 0700 "$SEED_DIR"
if [[ -f "$STATE_DIR/webui.passwd" ]]; then
  cp "$STATE_DIR/webui.passwd" "$SEED_DIR/webui.passwd"
  chmod 0600 "$SEED_DIR/webui.passwd"
  log "seeded shared WebUI password"
fi

# 2) Make the tuned config travel on the eMMC: promote the WebUI shadow config
#    to /etc so the clones boot with it (their empty NVMe has no shadow yet).
if [[ -f "$STATE_DIR/vision-gw.conf" ]]; then
  cp "$STATE_DIR/vision-gw.conf" /etc/vision-gw.conf
  sed -i "s#^GATEWAY_HOME=.*#GATEWAY_HOME=$GATEWAY_HOME#" /etc/vision-gw.conf || true
  log "promoted shadow config to /etc/vision-gw.conf"
fi
# Samba passdb and /etc/vision-nas.creds already live on the eMMC -> inherited.

# 3) Ensure an empty NVMe cannot wedge boot: the mirror mount must be nofail.
if grep -q "/srv/vision_mirror" /etc/fstab && ! grep -q "/srv/vision_mirror.*nofail" /etc/fstab; then
  sed -i "s#\(.*\s/srv/vision_mirror\s\+ext4\s\+\)\([^ ]*\)#\1nofail,\2#" /etc/fstab
  log "added nofail to /srv/vision_mirror fstab entry"
fi

# 4) Record whether the fleet should run with the read-only overlay, so
#    first-boot can re-enable it after personalising.
if [[ "${1:-}" == "--fleet-overlay" ]]; then
  touch "$SEED_DIR/enable-overlay"
  log "clones will re-enable read-only overlay on first boot"
fi

# 5) Strip per-unit identity (regenerated by first-boot).
log "stripping machine-id and SSH host keys"
truncate -s 0 /etc/machine-id || true
rm -f /var/lib/dbus/machine-id
rm -f /etc/ssh/ssh_host_*

log "clearing logs"
journalctl --rotate 2>/dev/null || true
journalctl --vacuum-time=1s 2>/dev/null || true
find /var/log -type f -exec truncate -s 0 {} + 2>/dev/null || true

hostnamectl set-hostname citostore-template 2>/dev/null || echo citostore-template > /etc/hostname

# 6) Arm first-boot personalisation and remove the completion flag.
rm -f /etc/citostore-firstboot-done
systemctl enable vision-firstboot.service 2>/dev/null || true

cat >&2 <<EOF

------------------------------------------------------------------
GOLDEN IMAGE PREPARED.

Next:
  1) sudo poweroff
  2) Put this board into eMMC/rpiboot mode, connect to the Win11 host.
  3) rpiboot.exe, then READ the eMMC to a .img
     (Raspberry Pi Imager, or  dd if=/dev/<emmc> of=citostore-golden.img ).
  4) Write that .img to each new unit, install its own empty NVMe, boot.
     first boot self-personalises (unique host id + its own NVMe) and,
     if you passed --fleet-overlay, re-enables the read-only overlay.
------------------------------------------------------------------
EOF
