#!/usr/bin/env bash
set -euo pipefail

# Optional NAS backup: an automounted CIFS share that nas-sync.sh rsyncs the
# mirror onto. Runs from apply-shadow-config.sh (every boot + WebUI apply);
#   60_configure_nas_optional.sh            enable with the configured values
#   60_configure_nas_optional.sh --disable  stop and remove it
#
# The mount units are GENERATED here with literal values. The static units this
# replaced used `What=%E{NAS_REMOTE}`, but in a unit file %E is the
# configuration-directory specifier (/etc), not an environment variable, and
# Environment= is ignored in [Unit]: systemd refused both units ("Where= setting
# doesn't match unit name"), so the NAS never mounted — and the failing restart
# aborted the rest of apply-shadow-config under set -e.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=/dev/null
source "$SCRIPT_DIR/../scripts/common.sh"

require_root

UNIT_DIR=/etc/systemd/system
MARKER="# Generated by 60_configure_nas_optional.sh"

# Every NAS mount/automount this script ever generated (the unit name follows
# the configured mount path, so it can change).
generated_units() {
  grep -l -F -x "$MARKER" "$UNIT_DIR"/*.mount "$UNIT_DIR"/*.automount 2>/dev/null || true
}

remove_generated() {
  local f
  while IFS= read -r f; do
    [[ -n "$f" ]] || continue
    systemctl disable --now "$(basename "$f")" >/dev/null 2>&1 || true
    rm -f "$f"
  done < <(generated_units)
}

if [[ "${1:-}" == "--disable" ]]; then
  systemctl disable --now nas-sync.timer >/dev/null 2>&1 || true
  remove_generated
  systemctl daemon-reload
  log "NAS backup disabled"
  exit 0
fi

if [[ -f /etc/vision-gw.conf ]]; then
  if grep -q '^NAS_ENABLED=' /etc/vision-gw.conf; then
    sed -i 's/^NAS_ENABLED=.*/NAS_ENABLED=true/' /etc/vision-gw.conf
  else
    echo 'NAS_ENABLED=true' >> /etc/vision-gw.conf
  fi
fi

load_config
: "${NAS_REMOTE:=//nas/vision}"
: "${NAS_MOUNT:=/mnt/nas}"
: "${NAS_CREDENTIALS:=/etc/vision-nas.creds}"

if [[ ! -f "$NAS_CREDENTIALS" ]]; then
  cp "$SCRIPT_DIR/../conf/nas/vision-nas.creds.example" "$NAS_CREDENTIALS"
  chmod 0600 "$NAS_CREDENTIALS"
  log "created $NAS_CREDENTIALS (edit credentials)"
fi

# Rewrite the full env file (never a NAS-only subset -- that dropped the
# SMB/WebUI/RTC/sync keys other units read).
write_gateway_env

# A mount unit's name must be its mount path, escaped.
unit=$(systemd-escape -p "$NAS_MOUNT")
remove_generated
mkdir -p "$NAS_MOUNT"
cat > "$UNIT_DIR/$unit.mount" <<EOF
$MARKER
[Unit]
Description=CitoStore NAS backup share
After=network-online.target
Wants=network-online.target

[Mount]
What=$NAS_REMOTE
Where=$NAS_MOUNT
Type=cifs
Options=credentials=$NAS_CREDENTIALS,iocharset=utf8,vers=3.0,_netdev,nofail
EOF
cat > "$UNIT_DIR/$unit.automount" <<EOF
$MARKER
[Unit]
Description=CitoStore NAS backup share (automount)

[Automount]
Where=$NAS_MOUNT
TimeoutIdleSec=600

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$unit.automount" >/dev/null 2>&1
systemctl restart "$unit.automount"
# --now: under the overlay timers.target is already active when this runs at
# boot, so a timer that is only enabled here would never start.
systemctl enable --now nas-sync.timer >/dev/null 2>&1

log "NAS backup enabled ($NAS_REMOTE on $NAS_MOUNT via $unit.automount)"
