#!/usr/bin/env bash
set -euo pipefail

# Audit batch 2 (2026-10-01), run against the real scripts in a throwaway
# Debian container with systemd installed (for systemd-escape/-analyze):
#   docker run --rm -v "$PWD:/src:ro" debian:bookworm bash -c \
#     'apt-get update -qq && apt-get install -y -qq systemd python3 >/dev/null; \
#      cp -r /src /gw && bash /gw/tests/functional/test_audit_batch2.sh'
# It writes to /etc and /run, so never run it on a real unit.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
GW=$(cd "$SCRIPT_DIR/../.." && pwd)
[[ $(id -u) -eq 0 ]] || { echo "run as root in a container" >&2; exit 1; }
[[ -f /.dockerenv ]] || { echo "refusing to run outside a container" >&2; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
fail=0
check() { if [[ "$2" == "$3" ]]; then echo "  PASS: $1"; else echo "  FAIL: $1 (got '$2', want '$3')"; fail=1; fi; }

# A systemctl that records and never touches anything.
mkdir -p "$TMP/bin"
cat > "$TMP/bin/systemctl" <<EOF
#!/bin/bash
echo "systemctl \$*" >> "$TMP/systemctl.log"
[[ "\$1" == "is-active" ]] && { [[ -f "$TMP/active" ]]; exit; }
exit 0
EOF
chmod +x "$TMP/bin/systemctl"
export PATH="$TMP/bin:$PATH"

echo "=== NAS units are generated with real paths and load ==="
printf 'NAS_ENABLED=true\nNAS_REMOTE=//nas.local/vision\nNAS_MOUNT=/mnt/nas\nNAS_CREDENTIALS=/etc/vision-nas.creds\nGATEWAY_HOME=%s\n' "$GW" > /etc/vision-gw.conf
: > "$TMP/systemctl.log"
GATEWAY_HOME="$GW" bash "$GW/install/60_configure_nas_optional.sh" >/dev/null 2>&1
check "mount unit named after the path" "$(test -f /etc/systemd/system/mnt-nas.mount && echo yes || echo no)" yes
check "  What= is the configured share (not /etc{NAS_REMOTE})" "$(sed -n 's/^What=//p' /etc/systemd/system/mnt-nas.mount)" "//nas.local/vision"
check "  Where= is the configured path" "$(sed -n 's/^Where=//p' /etc/systemd/system/mnt-nas.automount)" "/mnt/nas"
verify=$(SYSTEMD_LOG_LEVEL=err systemd-analyze verify /etc/systemd/system/mnt-nas.automount /etc/systemd/system/mnt-nas.mount 2>&1 | grep -iE "refusing|doesn't match|bad-setting|Unknown key" || true)
check "  systemd-analyze verify accepts both units" "$verify" ""
check "  nas-sync timer is started, not only enabled" "$(grep -c 'enable --now nas-sync.timer' "$TMP/systemctl.log")" 1
printf 'NAS_ENABLED=true\nNAS_REMOTE=//nas.local/vision\nNAS_MOUNT=/srv/nas-backup\nGATEWAY_HOME=%s\n' "$GW" > /etc/vision-gw.conf
GATEWAY_HOME="$GW" bash "$GW/install/60_configure_nas_optional.sh" >/dev/null 2>&1
check "changed mount path -> old units removed" "$(test -e /etc/systemd/system/mnt-nas.mount && echo yes || echo no)" no
check "  ... new escaped name" "$(test -f /etc/systemd/system/srv-nas\\x2dbackup.automount && echo yes || echo no)" yes
GATEWAY_HOME="$GW" bash "$GW/install/60_configure_nas_optional.sh" --disable >/dev/null 2>&1
check "--disable removes every generated unit" "$(grep -l -F -x '# Generated by 60_configure_nas_optional.sh' /etc/systemd/system/*.mount /etc/systemd/system/*.automount 2>/dev/null | wc -l)" 0

echo "=== apply-shadow-config: one failing step no longer skips the rest ==="
mkdir -p "$TMP/gwfake/scripts" "$TMP/gwfake/install" /srv/vision_mirror/.state
cp "$GW/scripts/apply-shadow-config.sh" "$GW/scripts/common.sh" "$TMP/gwfake/scripts/"
for s in scripts/update-config.sh install/50_configure_samba.sh install/70_configure_ingest.sh \
         install/75_configure_mdns.sh install/80_configure_mirror_ftp.sh install/60_configure_nas_optional.sh; do
  printf '#!/bin/bash\necho %s >> %s\nexit 0\n' "$(basename "$s")" "$TMP/ran" > "$TMP/gwfake/$s"
  chmod +x "$TMP/gwfake/$s"
done
printf '#!/bin/bash\necho 50_configure_samba.sh >> %s\nexit 1\n' "$TMP/ran" > "$TMP/gwfake/install/50_configure_samba.sh"
printf 'NAS_ENABLED=false\nGATEWAY_HOME=%s\n' "$TMP/gwfake" > /etc/vision-gw.conf
echo "NEW=1" > /srv/vision_mirror/.state/vision-gw.conf
echo "OLD=1" > /srv/vision_mirror/.state/vision-gw.conf.last-good
: > "$TMP/ran"
rc=0; GATEWAY_HOME="$TMP/gwfake" bash "$TMP/gwfake/scripts/apply-shadow-config.sh" >/dev/null 2>&1 || rc=$?
check "reports the failure (exit 1)" "$rc" 1
check "every later step still ran" "$(tr '\n' ' ' < "$TMP/ran")" "update-config.sh 50_configure_samba.sh 60_configure_nas_optional.sh 70_configure_ingest.sh 75_configure_mdns.sh 80_configure_mirror_ftp.sh "
check "last-good untouched by a config that failed to apply" "$(cat /srv/vision_mirror/.state/vision-gw.conf.last-good)" "OLD=1"
printf '#!/bin/bash\nexit 0\n' > "$TMP/gwfake/install/50_configure_samba.sh"
rc=0; GATEWAY_HOME="$TMP/gwfake" bash "$TMP/gwfake/scripts/apply-shadow-config.sh" >/dev/null 2>&1 || rc=$?
check "all steps ok -> exit 0" "$rc" 0
check "  ... and only now last-good = the applied config" "$(cat /srv/vision_mirror/.state/vision-gw.conf.last-good)" "NEW=1"

echo "=== write_if_changed / restart_if_needed ==="
# shellcheck source=/dev/null
source "$GW/scripts/common.sh"
echo a | write_if_changed "$TMP/f" && r=changed || r=same
check "new file -> changed" "$r" changed
echo a | write_if_changed "$TMP/f" && r=changed || r=same
check "identical content -> unchanged" "$r" same
touch "$TMP/active"; : > "$TMP/systemctl.log"
restart_if_needed false demo.service >/dev/null 2>&1
check "unchanged + running -> no restart" "$(grep -c 'restart demo' "$TMP/systemctl.log" || true)" 0
restart_if_needed true demo.service >/dev/null 2>&1
check "changed -> restart" "$(grep -c 'restart demo' "$TMP/systemctl.log")" 1
rm -f "$TMP/active"; : > "$TMP/systemctl.log"
restart_if_needed false demo.service >/dev/null 2>&1
check "not running -> (re)start" "$(grep -c 'restart demo' "$TMP/systemctl.log")" 1

echo "=== health-check survives a missing mirror and reports FAT repairs ==="
for c in mountpoint lvs lvremove fsck vgs; do printf '#!/bin/bash\nexit 1\n' > "$TMP/bin/$c"; chmod +x "$TMP/bin/$c"; done
printf '#!/bin/bash\necho "fixed 3 clusters"\nexit 1\n' > "$TMP/bin/fsck.fat"; chmod +x "$TMP/bin/fsck.fat"
mkdir -p "$TMP/dev/vg0"; touch "$TMP/dev/vg0/usb_0"
printf 'GATEWAY_HOME=%s\nUSB_LVS=(usb_0)\nLVM_VG=vg0\n' "$GW" > /etc/vision-gw.conf
rm -rf /srv/vision_mirror/.state /run/vision-health.json
rc=0; MIRROR_MOUNT=/srv/vision_mirror GATEWAY_HOME="$GW" bash "$GW/scripts/health-check.sh" >"$TMP/hc.out" 2>&1 || rc=$?
check "mirror not mounted -> health-check completes" "$rc" 0
check "  ... and writes the banner JSON" "$(grep -c 'mirror not mounted' /run/vision-health.json 2>/dev/null || echo 0)" 1
check "  ... without creating .state on the bare mountpoint" "$(test -d /srv/vision_mirror/.state && echo yes || echo no)" no

echo
if ((fail)); then echo "FAILED"; cat "$TMP/hc.out"; exit 1; fi
echo "ALL PASSED"
